# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJoinDiscord():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_joinDiscord(self):
    self.driver.get("https://discord.com/invite/romedao")
    self.driver.set_window_size(1440, 816)
    self.vars["number"] = len(self.driver.find_elements(By.CSS_SELECTOR, ".marginTop8-24uXGp > .contents-3ca1mk"))
    if self.driver.execute_script("return (arguments[0] == 1)", self.vars["number"]):
      self.driver.find_element(By.CSS_SELECTOR, ".marginTop8-24uXGp > .contents-3ca1mk").click()
      self.driver.find_element(By.NAME, "email").send_keys("00xsynth@gmail.com")
      self.driver.find_element(By.CSS_SELECTOR, ".wrapper-1f5byN").click()
      self.driver.find_element(By.NAME, "password").click()
      self.driver.find_element(By.NAME, "password").send_keys("GoingGhost?")
      self.driver.find_element(By.CSS_SELECTOR, ".button-1cRKG6").click()
      self.driver.close()
    else:
      self.driver.find_element(By.CSS_SELECTOR, ".marginTop40-Q4o1tS").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".anchor-1MIwyf")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".containerDefault-YUSmu3:nth-child(6) .channelName-3KPsGw")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".containerDefault-YUSmu3:nth-child(6) .channelName-3KPsGw").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.LINK_TEXT, "✅｜verify")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .reaction-2A2y9y .reactionCount-1zkLcN").click()
  
